export const typesWeather = {
  "01d": "/images/typesOfWea/clear_sky.svg",
  "01n": "/images/typesOfWea/clear_sky1.svg",
  "02d": "/images/typesOfWea/few_clouds.svg",
  "02n": "/images/typesOfWea/few_clouds2.svg",
  "03d": "/images/typesOfWea/scattered_clouds.svg",
  "03n": "/images/typesOfWea/scattered_clouds.svg",
  "04d": "/images/typesOfWea/broken_clouds.svg",
  "04n": "/images/typesOfWea/broken_clouds.svg",
  "09d": "/images/typesOfWea/shower_rain.svg",
  "09n": "/images/typesOfWea/shower_rain2.svg",
  "10d": "/images/typesOfWea/rain.svg",
  "10n": "/images/typesOfWea/rain.svg",
  "11d": "/images/typesOfWea/thunderstrom.svg",
  "11n": "/images/typesOfWea/thunderstrom.svg",
  "13d": "/images/typesOfWea/snow.svg",
  "13n": "/images/typesOfWea/snow.svg",
  "50d": "/images/typesOfWea/mist.svg",
  "50n": "/images/typesOfWea/mist.svg",
}